export const CARGANDO_CATEGORIAS_INICIO = "CARGANDO_CATEGORIAS_INICIO";
export const CARGANDO_CATEGORIAS_EXITO = "CARGANDO_CATEGORIAS_EXITO";
export const CARGANDO_CATEGORIAS_ERROR = "CARGANDO_CATEGORIAS_ERROR";