export const CARGANDO_PRODUCTOS_INICIO = "CARGANDO_PRODUCTOS_INICIO";
export const CARGANDO_PRODUCTOS_EXITO = "CARGANDO_PRODUCTOS_EXITO";
export const CARGANDO_PRODUCTOS_ERROR = "CARGANDO_PRODUCTOS_ERROR";