export const CARGANDO_COMPANIAS_INICIO = "CARGANDO_COMPANIAS_INICIO";
export const CARGANDO_COMPANIAS_EXITO = "CARGANDO_COMPANIAS_EXITO";
export const CARGANDO_COMPANIAS_ERROR = "CARGANDO_COMPANIAS_ERROR";